#--------------------------------------------------
# Install docker containers
#--------------------------------------------------

- name: Install latest version of docker
  become: yes
  yum:
    name: docker
    state: latest

- name: Start and enable docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

# - name: Enable repos
#   become: yes
#   shell: yum-config-manager --enable "{{ item }}" --save
#   with_items:
#   - rhel-server-rhscl-7-rpms

# - name: Install pip
#   become: yes
#   yum:
#     name: python27-python-pip
#     state: present

- name: Get the epel packages
  become: yes
  command: wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Install epel packages
  become: yes
  command: rpm -ivh epel-release-latest-7.noarch.rpm

- name: Install pip
  become: yes
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
  - { name: epel-release }
  - { name: python-pip }


# - name: Enable pip
#   command: scl enable python27 bash

# - name: Install latest version of pip
#   command: pip install --upgrade pip

- name: install certain python modules for docker
  become: yes
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker, version: 2.0.0 }
  - { name: docker-py, version: 1.10.6 }

- name: Make docker directory
  become: yes
  file:
    path:  "/home/{{ openshift_admin_username }}/dockyard"
    owner: "{{ openshift_admin_username }}"
    mode: 0755
    state: directory

- name: Clone SNX wetty
  git:
    repo: "https://github.com/Joel-Adams/snx-wetty.git"
    version: master
    dest: "/home/{{ openshift_admin_username }}/dockyard/snx-wetty"
    accept_hostkey: yes

- name: Clone SNX nginx
  git:
    repo: "https://github.com/Joel-Adams/snx-nginx.git"
    version: master
    dest: "/home/{{ openshift_admin_username }}/dockyard/snx-nginx"
    accept_hostkey: yes

- name: Template over nginx conf
  template:
    dest="/home/{{ openshift_admin_username }}/dockyard/snx-nginx/conf.d/proxy.conf"
    src=nginx.conf.j2

- name: Build Wetty Image
  become: yes
  docker_image:
     path: "/home/{{ openshift_admin_username }}/dockyard/snx-wetty"
     name: snx/wetty
     tag: latest

- name: Build Nginx Image
  become: yes
  docker_image:
     path: "/home/{{ openshift_admin_username }}/dockyard/snx-nginx"
     name: snx/nginx
     tag: latest

- name: Run the new wetty image
  become: yes
  command: docker run -d --name wetty-cntr --hostname wetty01 -v /etc/localtime:/etc/localtime:ro -p 127.0.0.1:3000:3000 snx/wetty:latest

- name: Run the new nginx image
  become: yes
  command: docker run -d --name nginx-proxy --hostname nginx-host01 -p 80:80 -p 443:443 --net="host" snx/nginx:latest
