#--------------------------------------------------
# Setup Bastion Firewall
#--------------------------------------------------

- name: Firewall exception https
  become: yes
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Firewall exception http
  become: yes
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Firewall exception port 3000
  become: yes
  firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled

- name: Firewall exception port 8080
  become: yes
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: Restart Firewall
  command: firewall-cmd --reload
