---
###################################
# Common Packages
###################################

- name: Template Ansible Hosts File
  template: dest="{{ lookup('env','PWD') }}/inventory/hosts"  src=hosts.j2
