#--------------------------------------------------
# Setup Nexus Container
#--------------------------------------------------

- name: Create a project
  openshift_raw:
    username: "{{ openshift_admin_username }}"
    password: "{{ openshift_password }}"
    api_version: v1
    kind: Project
    name: testing22
    description: Testing22
    display_name: "This is a test project."
    state: present
