---
#---------------------------------------------------
#  Azure Infra Creation
#---------------------------------------------------
- name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ resource_group_name }}"
    template_link: src=azure_template.j2
    parameters_link: src=azure_parameters.j2
